[package]
name       	= "counter"
version    	= "0.1.0"
description	= "Counter demo using dominator"
authors    	= ["Pauan <pauanyu+github@pm.me>"]
categories 	= ["wasm"]
readme     	= "README.md"
license    	= "MIT"
edition    	= "2018"

[workspace]

[dependencies]
console_error_panic_hook	= "0.1.6"
dominator               	= "0.5.18"
wasm-bindgen            	= "0.2.74"
futures-signals         	= "0.3.20"
once_cell               	= "1.7.2"
